/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Model.Address;
import Model.ContactInfo;
import Model.Person;

/**
 *
 * @author haohe
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private Person person;
    private Address address;
    private ContactInfo contactinfo;
    public MainJFrame() {
        initComponents();
        this.person = new Person();
        this.address= new Address();
        this.contactinfo=new ContactInfo();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fieldFirstName = new javax.swing.JTextField();
        fieldLastName = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        fieldCollegeName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        fieldApt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        fieldCity = new javax.swing.JTextField();
        fieldNUID = new javax.swing.JTextField();
        fieldPhoneNumber = new javax.swing.JTextField();
        fieldEmailID = new javax.swing.JTextField();
        fieldState = new javax.swing.JTextField();
        fieldStreetName = new javax.swing.JTextField();
        fieldZipCode = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        viewFirstName = new javax.swing.JLabel();
        viewLastName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        viewCollegeName = new javax.swing.JLabel();
        viewNUID = new javax.swing.JLabel();
        viewPhoneNumber = new javax.swing.JLabel();
        viewEmailID = new javax.swing.JLabel();
        viewStreetName = new javax.swing.JLabel();
        viewApt = new javax.swing.JLabel();
        viewCity = new javax.swing.JLabel();
        viewState = new javax.swing.JLabel();
        viewZipCode = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setAutoscrolls(true);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("FirstName");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 51, -1, -1));

        fieldFirstName.setText("          ");
        fieldFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldFirstNameActionPerformed(evt);
            }
        });
        jPanel2.add(fieldFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 51, 140, -1));

        fieldLastName.setText("          ");
        fieldLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldLastNameActionPerformed(evt);
            }
        });
        jPanel2.add(fieldLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 83, 140, -1));

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 520, -1, -1));

        jLabel5.setText("NUID");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 165, -1, -1));

        fieldCollegeName.setText("            ");
        fieldCollegeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCollegeNameActionPerformed(evt);
            }
        });
        jPanel2.add(fieldCollegeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 112, 140, -1));

        jLabel6.setText("LastName");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 79, -1, -1));

        jLabel7.setText("College Name");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel8.setText("Contact Information");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 209, -1, -1));

        jLabel9.setText("Phone number");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 250, -1, -1));

        jLabel10.setText("Email ID");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 294, -1, -1));

        fieldApt.setText("             ");
        jPanel2.add(fieldApt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 140, -1));

        jLabel11.setText("Address ");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 336, -1, -1));

        jLabel12.setText("StreetName");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 364, -1, -1));

        jLabel13.setText("Apt no.");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 398, -1, -1));

        jLabel14.setText("City");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 432, -1, -1));

        jLabel15.setText("State");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 466, -1, -1));

        jLabel16.setText("Zip code");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 488, -1, -1));

        fieldCity.setText("              ");
        jPanel2.add(fieldCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 140, -1));

        fieldNUID.setText("            ");
        jPanel2.add(fieldNUID, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 160, 140, -1));

        fieldPhoneNumber.setText("             ");
        jPanel2.add(fieldPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 140, -1));

        fieldEmailID.setText("           ");
        fieldEmailID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldEmailIDActionPerformed(evt);
            }
        });
        jPanel2.add(fieldEmailID, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 140, -1));

        fieldState.setText("           ");
        jPanel2.add(fieldState, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, 140, -1));

        fieldStreetName.setText("          ");
        jPanel2.add(fieldStreetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 140, -1));

        fieldZipCode.setText("         ");
        jPanel2.add(fieldZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 480, 140, -1));

        jSplitPane1.setLeftComponent(jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewFirstName.setText("firstName");
        jPanel3.add(viewFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        viewLastName.setText("lastName");
        jPanel3.add(viewLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 78, -1));

        jLabel3.setText(" ");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 238, -1, -1));

        jLabel4.setText(" ");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 284, -1, -1));

        viewCollegeName.setText("CollegeName");
        jPanel3.add(viewCollegeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        viewNUID.setText("NUID");
        jPanel3.add(viewNUID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        viewPhoneNumber.setText("phoneNumber");
        jPanel3.add(viewPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));

        viewEmailID.setText("emailID");
        jPanel3.add(viewEmailID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, -1));

        viewStreetName.setText("streetName");
        jPanel3.add(viewStreetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, -1, 10));

        viewApt.setText("apt");
        jPanel3.add(viewApt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, -1, -1));

        viewCity.setText("city");
        jPanel3.add(viewCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, -1, -1));

        viewState.setText("state");
        jPanel3.add(viewState, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, -1, -1));

        viewZipCode.setText("zipCode");
        jPanel3.add(viewZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, -1, -1));

        jLabel17.setText("First name");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel18.setText("Last name");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel19.setText("college");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel20.setText("NUID");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel21.setText("phone");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jLabel22.setText("Email");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        jLabel23.setText("Street");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        jLabel24.setText("apt");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        jLabel25.setText("city");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        jLabel26.setText("state");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, -1, -1));

        jLabel27.setText("zipCode");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, -1, -1));

        jSplitPane1.setRightComponent(jPanel3);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldLastNameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String firstName=fieldFirstName.getText();
        String lastName=fieldLastName.getText();
        String collegeName=fieldCollegeName.getText();
        String nuid=fieldNUID.getText();
        String phoneNumber=fieldPhoneNumber.getText();
        String emailID=fieldEmailID.getText();
      
        
        String streetName = fieldStreetName.getText();
        String aptNo=fieldApt.getText();
        String city=fieldCity.getText();
        String state=fieldState.getText();
        String zipCode=fieldZipCode.getText();
        //String contactinfo=field
        
        this.person.setFirstName(firstName);
        this.person.setLastName(lastName);
        this.person.setCollegeName(collegeName);
        this.person.setNUID(nuid);
        
        
        //this.person.setName(name);
        
        Address address=this.person.getAddress();
        ContactInfo contactInfo=this.person.getContactInfo();
        
        
        
        
        address.setStreetName(streetName);
        address.setApt(aptNo);
        address.setCity(city);
        address.setState(state);
        address.setZipCode(zipCode);
        contactInfo.setPhoneNumber(phoneNumber);
        contactInfo.setEmailID(emailID);
        
        display();
        
       
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void fieldFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldFirstNameActionPerformed

    private void fieldCollegeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCollegeNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCollegeNameActionPerformed

    private void fieldEmailIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldEmailIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldEmailIDActionPerformed
     private void display(){
         Person obj2=new Person();
         viewFirstName.setText(this.person.getFirstName());
       
         viewLastName.setText(this.person.getLastName());
         viewCollegeName.setText(this.person.getCollegeName());
         viewNUID.setText(this.person.getNUID());
         viewPhoneNumber.setText(this.person.getContactInfo().getPhoneNumber());
         viewEmailID.setText(this.person.getContactInfo().getEmailID());
         viewApt.setText(this.person.getAddress().getApt());
         viewCity.setText(this.person.getAddress().getCity());
         viewStreetName.setText(this.person.getAddress().getStreetName());
         viewState.setText(this.person.getAddress().getState());
         viewZipCode.setText(this.person.getAddress().getZipCode());
         //viewStreetName.setText(this.person.getAddress().getStreetName());
         
        
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fieldApt;
    private javax.swing.JTextField fieldCity;
    private javax.swing.JTextField fieldCollegeName;
    private javax.swing.JTextField fieldEmailID;
    private javax.swing.JTextField fieldFirstName;
    private javax.swing.JTextField fieldLastName;
    private javax.swing.JTextField fieldNUID;
    private javax.swing.JTextField fieldPhoneNumber;
    private javax.swing.JTextField fieldState;
    private javax.swing.JTextField fieldStreetName;
    private javax.swing.JTextField fieldZipCode;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel viewApt;
    private javax.swing.JLabel viewCity;
    private javax.swing.JLabel viewCollegeName;
    private javax.swing.JLabel viewEmailID;
    private javax.swing.JLabel viewFirstName;
    private javax.swing.JLabel viewLastName;
    private javax.swing.JLabel viewNUID;
    private javax.swing.JLabel viewPhoneNumber;
    private javax.swing.JLabel viewState;
    private javax.swing.JLabel viewStreetName;
    private javax.swing.JLabel viewZipCode;
    // End of variables declaration//GEN-END:variables
}
