/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Application;
import Model.Medicine;
import Model.MedicineCatalog;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author haohe
 */

//DefaultTableModel medTableModel;
public class CatalogJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CatalogJPanel
     */
    private Application application;
    DefaultTableModel medTableModel;
    
    public CatalogJPanel() {
        initComponents();
    }
    CatalogJPanel(Application application){
        initComponents();
        this.application=application;
        this.medTableModel=(DefaultTableModel)medicineCatalog.getModel();
        displayMedicineCatalog();
        
        //displayMedicineCatalog();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        medicineCatalog = new javax.swing.JTable();
        fieldName = new javax.swing.JTextField();
        fieldDosage = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        DELETE = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        medicineCatalog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Dosage"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(medicineCatalog);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 310, 290));

        fieldName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldNameFocusLost(evt);
            }
        });
        fieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNameActionPerformed(evt);
            }
        });
        add(fieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 150, 80));
        add(fieldDosage, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 150, 80));

        addButton.setText("ADD");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, -1));

        DELETE.setText("DELETE");
        DELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETEActionPerformed(evt);
            }
        });
        add(DELETE, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void fieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNameActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        String name=fieldName.getText();
        String dosage=fieldDosage.getText();
        MedicineCatalog catalog=this.application.getCatalog();
        catalog.createMedicine(name,Double.valueOf(dosage));
        
        displayMedicineCatalog();
    }//GEN-LAST:event_addButtonActionPerformed

    private void fieldNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldNameFocusLost
        // TODO add your handling code here:
        String name=fieldName.getText();
        Boolean isUnique = this.application.getCatalog().checkIfMedicineUnique(name);
        if(isUnique){
            
        } else{
            fieldName.setText("");
            JOptionPane.showMessageDialog(null,"Medicine already exist!");
        }
    }//GEN-LAST:event_fieldNameFocusLost

    private void DELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETEActionPerformed
        // TODO add your handling code here:
        int selectedRow = medicineCatalog.getSelectedRow();
        if(selectedRow>=0){
            Medicine med=(Medicine) medicineCatalog.getValueAt(selectedRow,0);
            this.application.getCatalog().removeMedicine(med.getMedicineName());
            displayMedicineCatalog();
        }else{
            
        }
    }//GEN-LAST:event_DELETEActionPerformed
 public void displayMedicineCatalog(){
        // check if the catalog is not empty
        ArrayList<Medicine> medicines=this.application.getCatalog().getMedicineList();
        if(medicines.size()>0){
            medTableModel.setRowCount(0);
            for(Medicine med: medicines){
                // row[] object for the table
                Object row[] = new Object[2];
                row[0]=med;
                row[1]=med.getDosage();
                medTableModel.addRow(row);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DELETE;
    private javax.swing.JButton addButton;
    private javax.swing.JTextField fieldDosage;
    private javax.swing.JTextField fieldName;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable medicineCatalog;
    // End of variables declaration//GEN-END:variables
}
