/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Application;
import Model.VitalSignHistory;
import javax.swing.JOptionPane;

/**
 *
 * @author haohe
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    private Application application;
   
    CreateJPanel(Application application){
        initComponents();
        this.application = application;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fieldObservationID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fieldTemperature1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fieldBloodPressure = new javax.swing.JTextField();
        addObservationButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Create a Vital Sign");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        fieldObservationID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldObservationIDActionPerformed(evt);
            }
        });
        add(fieldObservationID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 100, -1));

        jLabel2.setText("ID");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));
        add(fieldTemperature1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 100, -1));

        jLabel3.setText("Temperature");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, 30));

        jLabel4.setText("Blood Pressure");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));
        add(fieldBloodPressure, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 90, -1));

        addObservationButton.setText("Add Observation");
        addObservationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addObservationButtonActionPerformed(evt);
            }
        });
        add(addObservationButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void fieldObservationIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldObservationIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldObservationIDActionPerformed

    private void addObservationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addObservationButtonActionPerformed
        // TODO add your handling code here:
        // add an observation to vital signs history
        VitalSignHistory history = this.application.getHistory();
        // read the text fields
        String id=fieldObservationID.getText();
        String temperature = fieldTemperature1.getText();
        String bloodPressure = fieldBloodPressure.getText();
        
        //convert/cast and pass
        history.createObservation(Integer.valueOf(id),Double.valueOf(temperature),Double.valueOf(bloodPressure));
       
        JOptionPane.showMessageDialog(null,"Added");
    }//GEN-LAST:event_addObservationButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addObservationButton;
    private javax.swing.JTextField fieldBloodPressure;
    private javax.swing.JTextField fieldObservationID;
    private javax.swing.JTextField fieldTemperature1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
