/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Model.Application;
//import Model.Medicine;
//import java.util.ArrayList;

/**
 *
 * @author haohe
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    
    Application application;
    public MainJFrame() {
        initComponents();
        this.application= new Application();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPanel = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        ControlJPanel = new javax.swing.JPanel();
        CreateObservation = new javax.swing.JButton();
        viewVital = new javax.swing.JButton();
        MedicineCatalog = new javax.swing.JButton();
        assignButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 928, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 659, Short.MAX_VALUE)
        );

        jSplitPanel.setRightComponent(jPanel2);

        ControlJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CreateObservation.setText("Create Observation");
        CreateObservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateObservationActionPerformed(evt);
            }
        });
        ControlJPanel.add(CreateObservation, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        viewVital.setText("View vital sign history");
        viewVital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewVitalActionPerformed(evt);
            }
        });
        ControlJPanel.add(viewVital, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        MedicineCatalog.setText("Medicine Catalog");
        MedicineCatalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedicineCatalogActionPerformed(evt);
            }
        });
        ControlJPanel.add(MedicineCatalog, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 351, -1, -1));

        assignButton.setText("Assign Medicine");
        assignButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignButtonActionPerformed(evt);
            }
        });
        ControlJPanel.add(assignButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, -1, -1));

        jSplitPanel.setLeftComponent(ControlJPanel);

        getContentPane().add(jSplitPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreateObservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateObservationActionPerformed
        // TODO add your handling code here:
        jSplitPanel.setRightComponent(new CreateJPanel(this.application));
    }//GEN-LAST:event_CreateObservationActionPerformed

    private void viewVitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewVitalActionPerformed
        // TODO add your handling code here:
        jSplitPanel.setRightComponent(new viewJPanel(this.application));
    }//GEN-LAST:event_viewVitalActionPerformed

    private void MedicineCatalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedicineCatalogActionPerformed
        // TODO add your handling code here:
        jSplitPanel.setRightComponent(new CatalogJPanel(this.application));
    }//GEN-LAST:event_MedicineCatalogActionPerformed

    private void assignButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignButtonActionPerformed
        // TODO add your handling code here:
        jSplitPanel.setRightComponent(new MedicineAssignJPanel(this.application));
    }//GEN-LAST:event_assignButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ControlJPanel;
    private javax.swing.JButton CreateObservation;
    private javax.swing.JButton MedicineCatalog;
    private javax.swing.JButton assignButton;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPanel;
    private javax.swing.JButton viewVital;
    // End of variables declaration//GEN-END:variables
}
